name: Build and push Docker image to ECR
on:         
    workflow_dispatch:

env:
    AWS_REGION: eu-west-2
    ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
    ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
    IMAGE_TAG: ${{ github.sha }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write


        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure AWS credentials via OIDC
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ env.AWS_REGION }}
            role-session-name: github-ecr-ecs

        - name: Login to Amazon ECR
          run: |
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY

        - name: Build docker image
          run: docker build -f ./app/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app

        - name: Scan image for vulnerabilities
          uses: aquasecurity/trivy-action@v0.35.0
          with:
            image-ref: ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY}}:${{ env.IMAGE_TAG }}
            format: 'table'
            exit-code: '0'

        - name: Push docker image to ECR
          run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
