name: terraform plan

on:
  workflow_run:
    workflows: ["Build and push Docker image to ECR"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: terraform-plan
  cancel-in-progress: true

env:
    AWS_REGION: eu-west-2
    TF_VAR_route53_zone_id: ${{ vars.ROUTE53_ZONE_ID }}
    TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
   
jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

        permissions:
            contents: read
            id-token: write
            actions: read

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.workflow_run.head_sha || github.sha }}

        - name: Download image URI artifact
          if: ${{ github.event_name == 'workflow_run' }}
          uses: actions/download-artifact@v4
          with:
            name: image-uri
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Set image URI as environment variable
          run: |
            if [ "${{ github.event_name }}" == "workflow_run" ]; then 
              echo "TF_VAR_container_image=$(cat image-uri.txt)" >> $GITHUB_ENV  
              else
              SHORT_SHA=${GITHUB_SHA::8}
              echo "TF_VAR_container_image=${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:git-${SHORT_SHA}" >> $GITHUB_ENV  
            fi

        - name: Configure AWS credentials via OIDC
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TERRAFORM_PLAN }}
            aws-region: ${{ env.AWS_REGION }}
            role-session-name: terraform-plan

        - name: Setup TFLint
          uses: terraform-linters/setup-tflint@v3
          with:
            tflint_version: 0.34.1

        - name: Init TFLint
          run: tflint --init

        - name: Run TFLint
          run: tflint

        - name: Setup Checkov
          uses: bridgecrewio/checkov-action@v12
          with:
              directory: terraform
              soft_fail: true

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.14.3

        - name: Terraform Init
          working-directory: terraform
          run: terraform init

        - name: Terraform format
          working-directory: terraform
          run: terraform fmt -check

        - name: Terraform Validate
          working-directory: terraform
          run: terraform validate

        - name: Terraform Plan
          working-directory: terraform
          run: terraform plan -input=false -lock-timeout=2m -out=tfplan
      
        - name: Show Terraform Plan
          working-directory: terraform
          run: terraform show -no-color tfplan

        - name: Upload Terraform plan as artifact
          uses: actions/upload-artifact@v4
          with:
            name: terraform-plan
            path: |
              terraform/tfplan
              image-uri.txt

        - name: Notify success
          if: success()
          run: echo Success! Your terraform plan has been created successfully!
